image: mapiacompany/muzika-platform-server:latest

stages:
  - deploy

deploy:master:elb:
  stage: deploy
  variables:
    ZIP_FILE: "dist.zip"
  before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - cd ./muzika-contract && npm install && npm run contract:compile && cd ..
    - zip -r dist.zip ./ -x ".git/*" "venv/*" "deploy/*" ".idea/*" "*/__pycache__/*"
    - sh ./deploy/elb-deploy.sh
  only:
    - master

deploy:develop:
  stage: deploy
  variables:
    ZIP_FILE: "dist.zip"
  script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - cd ./muzika-contract && npm install && npm run contract:compile && cd ..
    - zip -r dist.zip ./ -x ".git/*" "venv/*" "deploy/*" ".idea/*" "*/__pycache__/*"
    - sh ./deploy/elb-deploy.sh
  only:
    - develop